# Cvmfs Client Configuration
cvmfs_role: client
galaxy_cvmfs_repos_enabled: true
galaxy_cvmfs_server_urls:
  - domain: galaxyproject.org
    urls:
      - "http://cvmfs1-ufr0.galaxyproject.eu/cvmfs/@fqrn@"
      - "http://cvmfs1-psu0.galaxyproject.org/cvmfs/@fqrn@"
      - "http://cvmfs-s1-galaxy.computecanada.ca:8000/cvmfs/@fqrn@"
      - "http://cvmfs1-iu0.galaxyproject.org/cvmfs/@fqrn@"
      - "http://cvmfs1-tacc0.galaxyproject.org/cvmfs/@fqrn@"
      - "http://cvmfs1-mel0.gvl.org.au/cvmfs/@fqrn@"

cvmfs_quota_limit: 10000
cvmfs_telemetry_send: "ON"
cvmfs_telemetry_rate: "60"
cvmfs_influx_host: localhost
cvmfs_influx_port: "8092"
cvmfs_influx_metric_name: cvmfs_metrics
cvmfs_influx_extra_tags: "{{ ansible_hostname }}"
cvmfs_influx_extra_fields: ""
