---
## NFS Tests
nfs_check_var_prefix: nfs_
nfs_check_mount_groups:
  - cvmfs
  - dnb
  - jwd
  - cache
  - misc
nfs_check_excluded_mounts: 
  - db
  - dnb04
  - dnb-ds01
  - 5
  - jwd01
  - jwd02f
  - jwd03f
  - jwd04
  - jwd05e
nfs_check_timeout_sec: 10
nfs_check_path: /usr/local/bin/check_nfs_access
## Firewall
firewall_public_services: []
firewall_internal_services: []
firewall_restart_daemon: true

galaxy_training: false
galaxy_group: training-pxe-test
galaxy_cluster: denbi
galaxy_docker_hack: true
startd_attrs:
  - GalaxyTraining
  - GalaxyGroup
  - GalaxyCluster
  - GalaxyDockerHack
rank: GalaxyGroup
base_cgroup: htcondor
memory_limit_policy: hard
reserved_memory: 2048

autofs_mount_points:
  - data
  - gxtest
  - gxkey
  - jwd
  - usrlocal
  - usrlocal_celerycluster # which is actually /opt/galaxy
  - cache
  - misc

## Telegraf
check_slx_disks_path: /usr/local/bin/check_slx_disks
telegraf_agent_config_path: /etc/telegraf
telegraf_plugins_extra:
  check_slx_disks_telegraf:
    plugin: exec
    config:
      - commands = ["{{ check_slx_disks_path }}"]
      - timeout = "2m"
      - data_format = "influx"
      - interval = "1m"
  check_nfs_access_telegraf:
    plugin: exec
    config:
      - commands = ["{{ nfs_check_path }}"]
      - timeout = "1m"
      - data_format = "influx"
      - interval = "1m"
